# =====================================================================
# TMUX CONFIGURATION FOR EMACS USERS: SET PREFIX TO CTRL+\
# =====================================================================

# reload with
# tmux source-file ~/.tmux.conf

# Unbind the default Ctrl+b prefix
unbind C-b

# Set the new global prefix to Ctrl+\
set-option -g prefix 'C-\'

# Allow hitting Ctrl+\ twice to pass the keystroke through to underlying apps
bind-key 'C-\' send-prefix
