[ids]
*

[main]
# Swaps CapsLock and Control
capslock = control
control = capslock

# Define the Emacs layer when holding Control (which is now the physical CapsLock key)
[control:C]
n = down
p = up
f = right
b = left
a = home
e = end
h = backspace
d = delete
k = S-end
